# Generated by Django 4.1.3 on 2022-11-29 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toDo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todos',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
