# Generated by Django 4.1.3 on 2022-11-30 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toDo', '0002_todos_updated_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchTerms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search', models.CharField(max_length=200)),
            ],
        ),
    ]
