# Generated by Django 4.1.3 on 2022-12-01 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toDo', '0003_searchterms'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todos',
            old_name='task',
            new_name='task_name',
        ),
        migrations.AlterField(
            model_name='todos',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
