# Generated by Django 4.1.3 on 2022-12-01 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toDo', '0004_rename_task_todos_task_name_alter_todos_updated_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todos',
            old_name='task_name',
            new_name='task',
        ),
    ]
